INFO 2025-01-21 15:10:22,722 controller 102502 -- Controller starting (version='2.40.0').
INFO 2025-01-21 15:10:22,728 controller 102502 -- Starting proxy on node 'cb879fbd0418dcb57ed445f1d8619c49333ef4f6ee0cf60352e6e7c5' listening on '0.0.0.0:8504'.
INFO 2025-01-21 15:10:23,264 controller 102502 -- Deploying new version of Deployment(name='MedicalInquiryService', app='default') (initial target replicas: 1).
INFO 2025-01-21 15:10:23,266 controller 102502 -- Deploying new version of Deployment(name='APIIngress', app='default') (initial target replicas: 1).
INFO 2025-01-21 15:10:23,369 controller 102502 -- Adding 1 replica to Deployment(name='MedicalInquiryService', app='default').
INFO 2025-01-21 15:10:23,370 controller 102502 -- Starting Replica(id='64elywmg', deployment='MedicalInquiryService', app='default').
INFO 2025-01-21 15:10:23,371 controller 102502 -- Adding 1 replica to Deployment(name='APIIngress', app='default').
INFO 2025-01-21 15:10:23,371 controller 102502 -- Starting Replica(id='blj0cqko', deployment='APIIngress', app='default').
INFO 2025-01-21 15:10:26,516 controller 102502 -- Replica(id='64elywmg', deployment='MedicalInquiryService', app='default') started successfully on node 'cb879fbd0418dcb57ed445f1d8619c49333ef4f6ee0cf60352e6e7c5' after 3.1s. Replica constructor, reconfigure method, and initial health check took 0.0s.
ERROR 2025-01-21 15:10:26,620 controller 102502 -- Exception in Replica(id='blj0cqko', deployment='APIIngress', app='default'), the replica will be stopped.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/deployment_state.py", line 696, in check_ready
    ) = ray.get(self._ready_obj_ref)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ServeReplica:default:APIIngress.initialize_and_get_metadata()[39m (pid=102504, ip=172.26.105.92, actor_id=b99bb4926254114c0944c88001000000, repr=<ray.serve._private.replica.ServeReplica:default:APIIngress object at 0x7fea0d14d280>)
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 872, in initialize_and_get_metadata
    await self._replica_impl.initialize(deployment_config)
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 616, in initialize
    raise RuntimeError(traceback.format_exc()) from None
RuntimeError: Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 598, in initialize
    self._user_callable_asgi_app = await asyncio.wrap_future(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 1137, in initialize_callable
    await self._callable._run_asgi_lifespan_startup()
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/http_util.py", line 486, in _run_asgi_lifespan_startup
    raise RuntimeError(
RuntimeError: ASGI lifespan startup failed. Check replica logs for details.
INFO 2025-01-21 15:10:26,622 controller 102502 -- Stopping Replica(id='blj0cqko', deployment='APIIngress', app='default') (currently ReplicaState.STARTING).
INFO 2025-01-21 15:10:26,624 controller 102502 -- Adding 1 replica to Deployment(name='APIIngress', app='default').
INFO 2025-01-21 15:10:26,624 controller 102502 -- Starting Replica(id='b13tu0jl', deployment='APIIngress', app='default').
INFO 2025-01-21 15:10:26,733 controller 102502 -- Replica(id='blj0cqko', deployment='APIIngress', app='default') is stopped.
ERROR 2025-01-21 15:10:29,848 controller 102502 -- Exception in Replica(id='b13tu0jl', deployment='APIIngress', app='default'), the replica will be stopped.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/deployment_state.py", line 696, in check_ready
    ) = ray.get(self._ready_obj_ref)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ServeReplica:default:APIIngress.initialize_and_get_metadata()[39m (pid=102506, ip=172.26.105.92, actor_id=2591b50434b7900466a1e59701000000, repr=<ray.serve._private.replica.ServeReplica:default:APIIngress object at 0x7fdbf845d640>)
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 872, in initialize_and_get_metadata
    await self._replica_impl.initialize(deployment_config)
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 616, in initialize
    raise RuntimeError(traceback.format_exc()) from None
RuntimeError: Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 598, in initialize
    self._user_callable_asgi_app = await asyncio.wrap_future(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 1137, in initialize_callable
    await self._callable._run_asgi_lifespan_startup()
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/http_util.py", line 486, in _run_asgi_lifespan_startup
    raise RuntimeError(
RuntimeError: ASGI lifespan startup failed. Check replica logs for details.
INFO 2025-01-21 15:10:29,848 controller 102502 -- Stopping Replica(id='b13tu0jl', deployment='APIIngress', app='default') (currently ReplicaState.STARTING).
INFO 2025-01-21 15:10:29,849 controller 102502 -- Adding 1 replica to Deployment(name='APIIngress', app='default').
INFO 2025-01-21 15:10:29,849 controller 102502 -- Starting Replica(id='ycx2npct', deployment='APIIngress', app='default').
INFO 2025-01-21 15:10:29,960 controller 102502 -- Replica(id='b13tu0jl', deployment='APIIngress', app='default') is stopped.
ERROR 2025-01-21 15:10:33,284 controller 102502 -- Exception in Replica(id='ycx2npct', deployment='APIIngress', app='default'), the replica will be stopped.
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/deployment_state.py", line 696, in check_ready
    ) = ray.get(self._ready_obj_ref)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::ServeReplica:default:APIIngress.initialize_and_get_metadata()[39m (pid=102501, ip=172.26.105.92, actor_id=e3c60490851962d6c0a3939d01000000, repr=<ray.serve._private.replica.ServeReplica:default:APIIngress object at 0x7f0ad8d81580>)
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 872, in initialize_and_get_metadata
    await self._replica_impl.initialize(deployment_config)
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 616, in initialize
    raise RuntimeError(traceback.format_exc()) from None
RuntimeError: Traceback (most recent call last):
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 598, in initialize
    self._user_callable_asgi_app = await asyncio.wrap_future(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/replica.py", line 1137, in initialize_callable
    await self._callable._run_asgi_lifespan_startup()
  File "/home/user/miniconda3/envs/mvp_server/lib/python3.12/site-packages/ray/serve/_private/http_util.py", line 486, in _run_asgi_lifespan_startup
    raise RuntimeError(
RuntimeError: ASGI lifespan startup failed. Check replica logs for details.
INFO 2025-01-21 15:10:33,285 controller 102502 -- Stopping Replica(id='ycx2npct', deployment='APIIngress', app='default') (currently ReplicaState.STARTING).
INFO 2025-01-21 15:10:33,286 controller 102502 -- Adding 1 replica to Deployment(name='APIIngress', app='default').
INFO 2025-01-21 15:10:33,286 controller 102502 -- Starting Replica(id='9jlr8z23', deployment='APIIngress', app='default').
ERROR 2025-01-21 15:10:33,290 controller 102502 -- The deployments ['APIIngress'] are UNHEALTHY.
INFO 2025-01-21 15:10:33,393 controller 102502 -- Controller shutdown started.
INFO 2025-01-21 15:10:33,395 controller 102502 -- Deleting app 'default'.
INFO 2025-01-21 15:10:33,398 controller 102502 -- Deleting Deployment(name='MedicalInquiryService', app='default')
INFO 2025-01-21 15:10:33,398 controller 102502 -- Deleting Deployment(name='APIIngress', app='default')
INFO 2025-01-21 15:10:33,413 controller 102502 -- Replica(id='ycx2npct', deployment='APIIngress', app='default') is stopped.
INFO 2025-01-21 15:10:33,414 controller 102502 -- Removing 1 replica from Deployment(name='MedicalInquiryService', app='default').
INFO 2025-01-21 15:10:33,414 controller 102502 -- Removing 1 replica from Deployment(name='APIIngress', app='default').
INFO 2025-01-21 15:10:33,414 controller 102502 -- Stopping Replica(id='64elywmg', deployment='MedicalInquiryService', app='default') (currently ReplicaState.RUNNING).
INFO 2025-01-21 15:10:33,416 controller 102502 -- Stopping Replica(id='9jlr8z23', deployment='APIIngress', app='default') (currently ReplicaState.STARTING).
INFO 2025-01-21 15:10:35,469 controller 102502 -- Replica(id='64elywmg', deployment='MedicalInquiryService', app='default') is stopped.
INFO 2025-01-21 15:10:36,329 controller 102502 -- Replica(id='9jlr8z23', deployment='APIIngress', app='default') is stopped.
WARNING 2025-01-21 15:10:36,437 controller 102502 -- All resources have shut down, controller exiting.
